# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ProjectCollaborator(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'role_name': 'str',
        'user_id': 'int',
        'name': 'str'
    }

    attribute_map = {
        'status': 'status',
        'role_name': 'role_name',
        'user_id': 'user_id',
        'name': 'name'
    }

    def __init__(self, status=None, role_name=None, user_id=None, name=None, _configuration=None):  # noqa: E501
        """ProjectCollaborator - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._role_name = None
        self._user_id = None
        self._name = None
        self.discriminator = None

        self.status = status
        self.role_name = role_name
        self.user_id = user_id
        self.name = name

    @property
    def status(self):
        """Gets the status of this ProjectCollaborator.  # noqa: E501

        Status of collaborator invitation  # noqa: E501

        :return: The status of this ProjectCollaborator.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ProjectCollaborator.

        Status of collaborator invitation  # noqa: E501

        :param status: The status of this ProjectCollaborator.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def role_name(self):
        """Gets the role_name of this ProjectCollaborator.  # noqa: E501

        Collaborator role  # noqa: E501

        :return: The role_name of this ProjectCollaborator.  # noqa: E501
        :rtype: str
        """
        return self._role_name

    @role_name.setter
    def role_name(self, role_name):
        """Sets the role_name of this ProjectCollaborator.

        Collaborator role  # noqa: E501

        :param role_name: The role_name of this ProjectCollaborator.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and role_name is None:
            raise ValueError("Invalid value for `role_name`, must not be `None`")  # noqa: E501

        self._role_name = role_name

    @property
    def user_id(self):
        """Gets the user_id of this ProjectCollaborator.  # noqa: E501

        Collaborator id  # noqa: E501

        :return: The user_id of this ProjectCollaborator.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ProjectCollaborator.

        Collaborator id  # noqa: E501

        :param user_id: The user_id of this ProjectCollaborator.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def name(self):
        """Gets the name of this ProjectCollaborator.  # noqa: E501

        Collaborator name  # noqa: E501

        :return: The name of this ProjectCollaborator.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectCollaborator.

        Collaborator name  # noqa: E501

        :param name: The name of this ProjectCollaborator.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectCollaborator, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectCollaborator):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectCollaborator):
            return True

        return self.to_dict() != other.to_dict()
