# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ProjectCompletePrivate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'funding': 'str',
        'funding_list': 'list[FundingInformation]',
        'description': 'str',
        'collaborators': 'list[Collaborator]',
        'quota': 'int',
        'used_quota': 'int',
        'created_date': 'str',
        'modified_date': 'str',
        'used_quota_private': 'int',
        'used_quota_public': 'int',
        'group_id': 'int',
        'account_id': 'int',
        'custom_fields': 'list[CustomArticleField]'
    }

    attribute_map = {
        'funding': 'funding',
        'funding_list': 'funding_list',
        'description': 'description',
        'collaborators': 'collaborators',
        'quota': 'quota',
        'used_quota': 'used_quota',
        'created_date': 'created_date',
        'modified_date': 'modified_date',
        'used_quota_private': 'used_quota_private',
        'used_quota_public': 'used_quota_public',
        'group_id': 'group_id',
        'account_id': 'account_id',
        'custom_fields': 'custom_fields'
    }

    def __init__(self, funding=None, funding_list=None, description=None, collaborators=None, quota=None, used_quota=None, created_date=None, modified_date=None, used_quota_private=None, used_quota_public=None, group_id=None, account_id=None, custom_fields=None, _configuration=None):  # noqa: E501
        """ProjectCompletePrivate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._funding = None
        self._funding_list = None
        self._description = None
        self._collaborators = None
        self._quota = None
        self._used_quota = None
        self._created_date = None
        self._modified_date = None
        self._used_quota_private = None
        self._used_quota_public = None
        self._group_id = None
        self._account_id = None
        self._custom_fields = None
        self.discriminator = None

        self.funding = funding
        self.funding_list = funding_list
        self.description = description
        self.collaborators = collaborators
        self.quota = quota
        self.used_quota = used_quota
        self.created_date = created_date
        self.modified_date = modified_date
        self.used_quota_private = used_quota_private
        self.used_quota_public = used_quota_public
        self.group_id = group_id
        self.account_id = account_id
        self.custom_fields = custom_fields

    @property
    def funding(self):
        """Gets the funding of this ProjectCompletePrivate.  # noqa: E501

        Project funding  # noqa: E501

        :return: The funding of this ProjectCompletePrivate.  # noqa: E501
        :rtype: str
        """
        return self._funding

    @funding.setter
    def funding(self, funding):
        """Sets the funding of this ProjectCompletePrivate.

        Project funding  # noqa: E501

        :param funding: The funding of this ProjectCompletePrivate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and funding is None:
            raise ValueError("Invalid value for `funding`, must not be `None`")  # noqa: E501

        self._funding = funding

    @property
    def funding_list(self):
        """Gets the funding_list of this ProjectCompletePrivate.  # noqa: E501

        Full Project funding information  # noqa: E501

        :return: The funding_list of this ProjectCompletePrivate.  # noqa: E501
        :rtype: list[FundingInformation]
        """
        return self._funding_list

    @funding_list.setter
    def funding_list(self, funding_list):
        """Sets the funding_list of this ProjectCompletePrivate.

        Full Project funding information  # noqa: E501

        :param funding_list: The funding_list of this ProjectCompletePrivate.  # noqa: E501
        :type: list[FundingInformation]
        """
        if self._configuration.client_side_validation and funding_list is None:
            raise ValueError("Invalid value for `funding_list`, must not be `None`")  # noqa: E501

        self._funding_list = funding_list

    @property
    def description(self):
        """Gets the description of this ProjectCompletePrivate.  # noqa: E501

        Project description  # noqa: E501

        :return: The description of this ProjectCompletePrivate.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProjectCompletePrivate.

        Project description  # noqa: E501

        :param description: The description of this ProjectCompletePrivate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def collaborators(self):
        """Gets the collaborators of this ProjectCompletePrivate.  # noqa: E501

        List of project collaborators  # noqa: E501

        :return: The collaborators of this ProjectCompletePrivate.  # noqa: E501
        :rtype: list[Collaborator]
        """
        return self._collaborators

    @collaborators.setter
    def collaborators(self, collaborators):
        """Sets the collaborators of this ProjectCompletePrivate.

        List of project collaborators  # noqa: E501

        :param collaborators: The collaborators of this ProjectCompletePrivate.  # noqa: E501
        :type: list[Collaborator]
        """
        if self._configuration.client_side_validation and collaborators is None:
            raise ValueError("Invalid value for `collaborators`, must not be `None`")  # noqa: E501

        self._collaborators = collaborators

    @property
    def quota(self):
        """Gets the quota of this ProjectCompletePrivate.  # noqa: E501

        Project quota  # noqa: E501

        :return: The quota of this ProjectCompletePrivate.  # noqa: E501
        :rtype: int
        """
        return self._quota

    @quota.setter
    def quota(self, quota):
        """Sets the quota of this ProjectCompletePrivate.

        Project quota  # noqa: E501

        :param quota: The quota of this ProjectCompletePrivate.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and quota is None:
            raise ValueError("Invalid value for `quota`, must not be `None`")  # noqa: E501

        self._quota = quota

    @property
    def used_quota(self):
        """Gets the used_quota of this ProjectCompletePrivate.  # noqa: E501

        Project used quota  # noqa: E501

        :return: The used_quota of this ProjectCompletePrivate.  # noqa: E501
        :rtype: int
        """
        return self._used_quota

    @used_quota.setter
    def used_quota(self, used_quota):
        """Sets the used_quota of this ProjectCompletePrivate.

        Project used quota  # noqa: E501

        :param used_quota: The used_quota of this ProjectCompletePrivate.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and used_quota is None:
            raise ValueError("Invalid value for `used_quota`, must not be `None`")  # noqa: E501

        self._used_quota = used_quota

    @property
    def created_date(self):
        """Gets the created_date of this ProjectCompletePrivate.  # noqa: E501

        Date when project was created  # noqa: E501

        :return: The created_date of this ProjectCompletePrivate.  # noqa: E501
        :rtype: str
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this ProjectCompletePrivate.

        Date when project was created  # noqa: E501

        :param created_date: The created_date of this ProjectCompletePrivate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and created_date is None:
            raise ValueError("Invalid value for `created_date`, must not be `None`")  # noqa: E501

        self._created_date = created_date

    @property
    def modified_date(self):
        """Gets the modified_date of this ProjectCompletePrivate.  # noqa: E501

        Date when project was last modified  # noqa: E501

        :return: The modified_date of this ProjectCompletePrivate.  # noqa: E501
        :rtype: str
        """
        return self._modified_date

    @modified_date.setter
    def modified_date(self, modified_date):
        """Sets the modified_date of this ProjectCompletePrivate.

        Date when project was last modified  # noqa: E501

        :param modified_date: The modified_date of this ProjectCompletePrivate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and modified_date is None:
            raise ValueError("Invalid value for `modified_date`, must not be `None`")  # noqa: E501

        self._modified_date = modified_date

    @property
    def used_quota_private(self):
        """Gets the used_quota_private of this ProjectCompletePrivate.  # noqa: E501

        Project private quota used  # noqa: E501

        :return: The used_quota_private of this ProjectCompletePrivate.  # noqa: E501
        :rtype: int
        """
        return self._used_quota_private

    @used_quota_private.setter
    def used_quota_private(self, used_quota_private):
        """Sets the used_quota_private of this ProjectCompletePrivate.

        Project private quota used  # noqa: E501

        :param used_quota_private: The used_quota_private of this ProjectCompletePrivate.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and used_quota_private is None:
            raise ValueError("Invalid value for `used_quota_private`, must not be `None`")  # noqa: E501

        self._used_quota_private = used_quota_private

    @property
    def used_quota_public(self):
        """Gets the used_quota_public of this ProjectCompletePrivate.  # noqa: E501

        Project public quota used  # noqa: E501

        :return: The used_quota_public of this ProjectCompletePrivate.  # noqa: E501
        :rtype: int
        """
        return self._used_quota_public

    @used_quota_public.setter
    def used_quota_public(self, used_quota_public):
        """Sets the used_quota_public of this ProjectCompletePrivate.

        Project public quota used  # noqa: E501

        :param used_quota_public: The used_quota_public of this ProjectCompletePrivate.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and used_quota_public is None:
            raise ValueError("Invalid value for `used_quota_public`, must not be `None`")  # noqa: E501

        self._used_quota_public = used_quota_public

    @property
    def group_id(self):
        """Gets the group_id of this ProjectCompletePrivate.  # noqa: E501

        Group of project if any  # noqa: E501

        :return: The group_id of this ProjectCompletePrivate.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this ProjectCompletePrivate.

        Group of project if any  # noqa: E501

        :param group_id: The group_id of this ProjectCompletePrivate.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and group_id is None:
            raise ValueError("Invalid value for `group_id`, must not be `None`")  # noqa: E501

        self._group_id = group_id

    @property
    def account_id(self):
        """Gets the account_id of this ProjectCompletePrivate.  # noqa: E501

        ID of the account owning the project  # noqa: E501

        :return: The account_id of this ProjectCompletePrivate.  # noqa: E501
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this ProjectCompletePrivate.

        ID of the account owning the project  # noqa: E501

        :param account_id: The account_id of this ProjectCompletePrivate.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and account_id is None:
            raise ValueError("Invalid value for `account_id`, must not be `None`")  # noqa: E501

        self._account_id = account_id

    @property
    def custom_fields(self):
        """Gets the custom_fields of this ProjectCompletePrivate.  # noqa: E501

        Collection custom fields  # noqa: E501

        :return: The custom_fields of this ProjectCompletePrivate.  # noqa: E501
        :rtype: list[CustomArticleField]
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this ProjectCompletePrivate.

        Collection custom fields  # noqa: E501

        :param custom_fields: The custom_fields of this ProjectCompletePrivate.  # noqa: E501
        :type: list[CustomArticleField]
        """
        if self._configuration.client_side_validation and custom_fields is None:
            raise ValueError("Invalid value for `custom_fields`, must not be `None`")  # noqa: E501

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectCompletePrivate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectCompletePrivate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectCompletePrivate):
            return True

        return self.to_dict() != other.to_dict()
