# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Resource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'title': 'str',
        'doi': 'str',
        'link': 'str',
        'status': 'str',
        'version': 'int'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'doi': 'doi',
        'link': 'link',
        'status': 'status',
        'version': 'version'
    }

    def __init__(self, id='', title='', doi='', link='', status='', version=0, _configuration=None):  # noqa: E501
        """Resource - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._title = None
        self._doi = None
        self._link = None
        self._status = None
        self._version = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if doi is not None:
            self.doi = doi
        if link is not None:
            self.link = link
        if status is not None:
            self.status = status
        if version is not None:
            self.version = version

    @property
    def id(self):
        """Gets the id of this Resource.  # noqa: E501

        ID of resource item  # noqa: E501

        :return: The id of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Resource.

        ID of resource item  # noqa: E501

        :param id: The id of this Resource.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                id is not None and len(id) > 255):
            raise ValueError("Invalid value for `id`, length must be less than or equal to `255`")  # noqa: E501

        self._id = id

    @property
    def title(self):
        """Gets the title of this Resource.  # noqa: E501

        Title of resource item  # noqa: E501

        :return: The title of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Resource.

        Title of resource item  # noqa: E501

        :param title: The title of this Resource.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                title is not None and len(title) > 1000):
            raise ValueError("Invalid value for `title`, length must be less than or equal to `1000`")  # noqa: E501

        self._title = title

    @property
    def doi(self):
        """Gets the doi of this Resource.  # noqa: E501

        DOI of resource item  # noqa: E501

        :return: The doi of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._doi

    @doi.setter
    def doi(self, doi):
        """Sets the doi of this Resource.

        DOI of resource item  # noqa: E501

        :param doi: The doi of this Resource.  # noqa: E501
        :type: str
        """

        self._doi = doi

    @property
    def link(self):
        """Gets the link of this Resource.  # noqa: E501

        Link of resource item  # noqa: E501

        :return: The link of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this Resource.

        Link of resource item  # noqa: E501

        :param link: The link of this Resource.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                link is not None and len(link) > 255):
            raise ValueError("Invalid value for `link`, length must be less than or equal to `255`")  # noqa: E501

        self._link = link

    @property
    def status(self):
        """Gets the status of this Resource.  # noqa: E501

        Status of resource item  # noqa: E501

        :return: The status of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Resource.

        Status of resource item  # noqa: E501

        :param status: The status of this Resource.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                status is not None and len(status) > 100):
            raise ValueError("Invalid value for `status`, length must be less than or equal to `100`")  # noqa: E501

        self._status = status

    @property
    def version(self):
        """Gets the version of this Resource.  # noqa: E501

        Version of resource item  # noqa: E501

        :return: The version of this Resource.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Resource.

        Version of resource item  # noqa: E501

        :param version: The version of this Resource.  # noqa: E501
        :type: int
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Resource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Resource):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Resource):
            return True

        return self.to_dict() != other.to_dict()
