# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ShortAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'institution_id': 'int',
        'email': 'str',
        'active': 'int',
        'institution_user_id': 'str',
        'quota': 'int',
        'used_quota': 'int',
        'user_id': 'int',
        'orcid_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'institution_id': 'institution_id',
        'email': 'email',
        'active': 'active',
        'institution_user_id': 'institution_user_id',
        'quota': 'quota',
        'used_quota': 'used_quota',
        'user_id': 'user_id',
        'orcid_id': 'orcid_id'
    }

    def __init__(self, id=None, first_name=None, last_name=None, institution_id=None, email=None, active=None, institution_user_id=None, quota=None, used_quota=None, user_id=None, orcid_id=None, _configuration=None):  # noqa: E501
        """ShortAccount - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._first_name = None
        self._last_name = None
        self._institution_id = None
        self._email = None
        self._active = None
        self._institution_user_id = None
        self._quota = None
        self._used_quota = None
        self._user_id = None
        self._orcid_id = None
        self.discriminator = None

        self.id = id
        self.first_name = first_name
        self.last_name = last_name
        self.institution_id = institution_id
        self.email = email
        self.active = active
        self.institution_user_id = institution_user_id
        self.quota = quota
        self.used_quota = used_quota
        self.user_id = user_id
        self.orcid_id = orcid_id

    @property
    def id(self):
        """Gets the id of this ShortAccount.  # noqa: E501

        Account id  # noqa: E501

        :return: The id of this ShortAccount.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ShortAccount.

        Account id  # noqa: E501

        :param id: The id of this ShortAccount.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def first_name(self):
        """Gets the first_name of this ShortAccount.  # noqa: E501

        First Name  # noqa: E501

        :return: The first_name of this ShortAccount.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this ShortAccount.

        First Name  # noqa: E501

        :param first_name: The first_name of this ShortAccount.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this ShortAccount.  # noqa: E501

        Last Name  # noqa: E501

        :return: The last_name of this ShortAccount.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this ShortAccount.

        Last Name  # noqa: E501

        :param last_name: The last_name of this ShortAccount.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def institution_id(self):
        """Gets the institution_id of this ShortAccount.  # noqa: E501

        Account institution  # noqa: E501

        :return: The institution_id of this ShortAccount.  # noqa: E501
        :rtype: int
        """
        return self._institution_id

    @institution_id.setter
    def institution_id(self, institution_id):
        """Sets the institution_id of this ShortAccount.

        Account institution  # noqa: E501

        :param institution_id: The institution_id of this ShortAccount.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and institution_id is None:
            raise ValueError("Invalid value for `institution_id`, must not be `None`")  # noqa: E501

        self._institution_id = institution_id

    @property
    def email(self):
        """Gets the email of this ShortAccount.  # noqa: E501

        User email  # noqa: E501

        :return: The email of this ShortAccount.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ShortAccount.

        User email  # noqa: E501

        :param email: The email of this ShortAccount.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def active(self):
        """Gets the active of this ShortAccount.  # noqa: E501

        Account activity status  # noqa: E501

        :return: The active of this ShortAccount.  # noqa: E501
        :rtype: int
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this ShortAccount.

        Account activity status  # noqa: E501

        :param active: The active of this ShortAccount.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501

        self._active = active

    @property
    def institution_user_id(self):
        """Gets the institution_user_id of this ShortAccount.  # noqa: E501

        Account institution user id  # noqa: E501

        :return: The institution_user_id of this ShortAccount.  # noqa: E501
        :rtype: str
        """
        return self._institution_user_id

    @institution_user_id.setter
    def institution_user_id(self, institution_user_id):
        """Sets the institution_user_id of this ShortAccount.

        Account institution user id  # noqa: E501

        :param institution_user_id: The institution_user_id of this ShortAccount.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and institution_user_id is None:
            raise ValueError("Invalid value for `institution_user_id`, must not be `None`")  # noqa: E501

        self._institution_user_id = institution_user_id

    @property
    def quota(self):
        """Gets the quota of this ShortAccount.  # noqa: E501

        Total storage available to account, in bytes  # noqa: E501

        :return: The quota of this ShortAccount.  # noqa: E501
        :rtype: int
        """
        return self._quota

    @quota.setter
    def quota(self, quota):
        """Sets the quota of this ShortAccount.

        Total storage available to account, in bytes  # noqa: E501

        :param quota: The quota of this ShortAccount.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and quota is None:
            raise ValueError("Invalid value for `quota`, must not be `None`")  # noqa: E501

        self._quota = quota

    @property
    def used_quota(self):
        """Gets the used_quota of this ShortAccount.  # noqa: E501

        Storage used by the account, in bytes  # noqa: E501

        :return: The used_quota of this ShortAccount.  # noqa: E501
        :rtype: int
        """
        return self._used_quota

    @used_quota.setter
    def used_quota(self, used_quota):
        """Sets the used_quota of this ShortAccount.

        Storage used by the account, in bytes  # noqa: E501

        :param used_quota: The used_quota of this ShortAccount.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and used_quota is None:
            raise ValueError("Invalid value for `used_quota`, must not be `None`")  # noqa: E501

        self._used_quota = used_quota

    @property
    def user_id(self):
        """Gets the user_id of this ShortAccount.  # noqa: E501

        User id associated with account, useful for example for adding the account as an author to an item  # noqa: E501

        :return: The user_id of this ShortAccount.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ShortAccount.

        User id associated with account, useful for example for adding the account as an author to an item  # noqa: E501

        :param user_id: The user_id of this ShortAccount.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def orcid_id(self):
        """Gets the orcid_id of this ShortAccount.  # noqa: E501

        ORCID iD associated to account  # noqa: E501

        :return: The orcid_id of this ShortAccount.  # noqa: E501
        :rtype: str
        """
        return self._orcid_id

    @orcid_id.setter
    def orcid_id(self, orcid_id):
        """Sets the orcid_id of this ShortAccount.

        ORCID iD associated to account  # noqa: E501

        :param orcid_id: The orcid_id of this ShortAccount.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and orcid_id is None:
            raise ValueError("Invalid value for `orcid_id`, must not be `None`")  # noqa: E501

        self._orcid_id = orcid_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShortAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShortAccount):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ShortAccount):
            return True

        return self.to_dict() != other.to_dict()
