# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ShortCustomField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'field_type': 'str',
        'settings': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'field_type': 'field_type',
        'settings': 'settings'
    }

    def __init__(self, id=None, name=None, field_type=None, settings=None, _configuration=None):  # noqa: E501
        """ShortCustomField - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._field_type = None
        self._settings = None
        self.discriminator = None

        self.id = id
        self.name = name
        self.field_type = field_type
        if settings is not None:
            self.settings = settings

    @property
    def id(self):
        """Gets the id of this ShortCustomField.  # noqa: E501

        Custom field id  # noqa: E501

        :return: The id of this ShortCustomField.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ShortCustomField.

        Custom field id  # noqa: E501

        :param id: The id of this ShortCustomField.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ShortCustomField.  # noqa: E501

        Custom field name  # noqa: E501

        :return: The name of this ShortCustomField.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ShortCustomField.

        Custom field name  # noqa: E501

        :param name: The name of this ShortCustomField.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def field_type(self):
        """Gets the field_type of this ShortCustomField.  # noqa: E501

        Custom field type  # noqa: E501

        :return: The field_type of this ShortCustomField.  # noqa: E501
        :rtype: str
        """
        return self._field_type

    @field_type.setter
    def field_type(self, field_type):
        """Sets the field_type of this ShortCustomField.

        Custom field type  # noqa: E501

        :param field_type: The field_type of this ShortCustomField.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and field_type is None:
            raise ValueError("Invalid value for `field_type`, must not be `None`")  # noqa: E501
        allowed_values = ["text", "textarea", "dropdown", "url", "email", "date", "dropdown_large_list"]  # noqa: E501
        if (self._configuration.client_side_validation and
                field_type not in allowed_values):
            raise ValueError(
                "Invalid value for `field_type` ({0}), must be one of {1}"  # noqa: E501
                .format(field_type, allowed_values)
            )

        self._field_type = field_type

    @property
    def settings(self):
        """Gets the settings of this ShortCustomField.  # noqa: E501

        Settings for the custom field  # noqa: E501

        :return: The settings of this ShortCustomField.  # noqa: E501
        :rtype: object
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this ShortCustomField.

        Settings for the custom field  # noqa: E501

        :param settings: The settings of this ShortCustomField.  # noqa: E501
        :type: object
        """

        self._settings = settings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShortCustomField, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShortCustomField):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ShortCustomField):
            return True

        return self.to_dict() != other.to_dict()
