# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.other_api import OtherApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOtherApi(unittest.TestCase):
    """OtherApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.other_api.OtherApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_categories_list(self):
        """Test case for categories_list

        Public Categories  # noqa: E501
        """
        pass

    def test_file_download(self):
        """Test case for file_download

        Public File Download  # noqa: E501
        """
        pass

    def test_item_types_list(self):
        """Test case for item_types_list

        Item Types  # noqa: E501
        """
        pass

    def test_licenses_list(self):
        """Test case for licenses_list

        Public Licenses  # noqa: E501
        """
        pass

    def test_private_account(self):
        """Test case for private_account

        Private Account information  # noqa: E501
        """
        pass

    def test_private_funding_search(self):
        """Test case for private_funding_search

        Search Funding  # noqa: E501
        """
        pass

    def test_private_licenses_list(self):
        """Test case for private_licenses_list

        Private Account Licenses  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
