# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projects_api import ProjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.projects_api.ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_private_project_article_delete(self):
        """Test case for private_project_article_delete

        Delete project article  # noqa: E501
        """
        pass

    def test_private_project_article_details(self):
        """Test case for private_project_article_details

        Project article details  # noqa: E501
        """
        pass

    def test_private_project_article_file(self):
        """Test case for private_project_article_file

        Project article file details  # noqa: E501
        """
        pass

    def test_private_project_article_files(self):
        """Test case for private_project_article_files

        Project article list files  # noqa: E501
        """
        pass

    def test_private_project_articles_create(self):
        """Test case for private_project_articles_create

        Create project article  # noqa: E501
        """
        pass

    def test_private_project_articles_list(self):
        """Test case for private_project_articles_list

        List project articles  # noqa: E501
        """
        pass

    def test_private_project_collaborator_delete(self):
        """Test case for private_project_collaborator_delete

        Remove project collaborator  # noqa: E501
        """
        pass

    def test_private_project_collaborators_invite(self):
        """Test case for private_project_collaborators_invite

        Invite project collaborators  # noqa: E501
        """
        pass

    def test_private_project_collaborators_list(self):
        """Test case for private_project_collaborators_list

        List project collaborators  # noqa: E501
        """
        pass

    def test_private_project_create(self):
        """Test case for private_project_create

        Create project  # noqa: E501
        """
        pass

    def test_private_project_delete(self):
        """Test case for private_project_delete

        Delete project  # noqa: E501
        """
        pass

    def test_private_project_details(self):
        """Test case for private_project_details

        View project details  # noqa: E501
        """
        pass

    def test_private_project_leave(self):
        """Test case for private_project_leave

        Private Project Leave  # noqa: E501
        """
        pass

    def test_private_project_note(self):
        """Test case for private_project_note

        Project note details  # noqa: E501
        """
        pass

    def test_private_project_note_delete(self):
        """Test case for private_project_note_delete

        Delete project note  # noqa: E501
        """
        pass

    def test_private_project_note_update(self):
        """Test case for private_project_note_update

        Update project note  # noqa: E501
        """
        pass

    def test_private_project_notes_create(self):
        """Test case for private_project_notes_create

        Create project note  # noqa: E501
        """
        pass

    def test_private_project_notes_list(self):
        """Test case for private_project_notes_list

        List project notes  # noqa: E501
        """
        pass

    def test_private_project_publish(self):
        """Test case for private_project_publish

        Private Project Publish  # noqa: E501
        """
        pass

    def test_private_project_update(self):
        """Test case for private_project_update

        Update project  # noqa: E501
        """
        pass

    def test_private_projects_list(self):
        """Test case for private_projects_list

        Private Projects  # noqa: E501
        """
        pass

    def test_private_projects_search(self):
        """Test case for private_projects_search

        Private Projects search  # noqa: E501
        """
        pass

    def test_project_articles(self):
        """Test case for project_articles

        Public Project Articles  # noqa: E501
        """
        pass

    def test_project_details(self):
        """Test case for project_details

        Public Project  # noqa: E501
        """
        pass

    def test_projects_list(self):
        """Test case for projects_list

        Public Projects  # noqa: E501
        """
        pass

    def test_projects_search(self):
        """Test case for projects_search

        Public Projects Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
