# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.error_message import ErrorMessage  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorMessage(unittest.TestCase):
    """ErrorMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorMessage(self):
        """Test ErrorMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_message.ErrorMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
