# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.institution_accounts_search import InstitutionAccountsSearch  # noqa: E501
from swagger_client.rest import ApiException


class TestInstitutionAccountsSearch(unittest.TestCase):
    """InstitutionAccountsSearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstitutionAccountsSearch(self):
        """Test InstitutionAccountsSearch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.institution_accounts_search.InstitutionAccountsSearch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
