# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.funding_search import FundingSearch  # noqa: E501
from swagger_client.rest import ApiException


class TestFundingSearch(unittest.TestCase):
    """FundingSearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFundingSearch(self):
        """Test FundingSearch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.funding_search.FundingSearch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
