# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.collections_api import CollectionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.collections_api.CollectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_collection_articles(self):
        """Test case for collection_articles

        Public Collection Articles  # noqa: E501
        """
        pass

    def test_collection_details(self):
        """Test case for collection_details

        Collection details  # noqa: E501
        """
        pass

    def test_collection_version_details(self):
        """Test case for collection_version_details

        Collection Version details  # noqa: E501
        """
        pass

    def test_collection_versions(self):
        """Test case for collection_versions

        Collection Versions list  # noqa: E501
        """
        pass

    def test_collections_list(self):
        """Test case for collections_list

        Public Collections  # noqa: E501
        """
        pass

    def test_collections_search(self):
        """Test case for collections_search

        Public Collections Search  # noqa: E501
        """
        pass

    def test_private_collection_article_delete(self):
        """Test case for private_collection_article_delete

        Delete collection article  # noqa: E501
        """
        pass

    def test_private_collection_articles_add(self):
        """Test case for private_collection_articles_add

        Add collection articles  # noqa: E501
        """
        pass

    def test_private_collection_articles_list(self):
        """Test case for private_collection_articles_list

        List collection articles  # noqa: E501
        """
        pass

    def test_private_collection_articles_replace(self):
        """Test case for private_collection_articles_replace

        Replace collection articles  # noqa: E501
        """
        pass

    def test_private_collection_author_delete(self):
        """Test case for private_collection_author_delete

        Delete collection author  # noqa: E501
        """
        pass

    def test_private_collection_authors_add(self):
        """Test case for private_collection_authors_add

        Add collection authors  # noqa: E501
        """
        pass

    def test_private_collection_authors_list(self):
        """Test case for private_collection_authors_list

        List collection authors  # noqa: E501
        """
        pass

    def test_private_collection_authors_replace(self):
        """Test case for private_collection_authors_replace

        Replace collection authors  # noqa: E501
        """
        pass

    def test_private_collection_categories_add(self):
        """Test case for private_collection_categories_add

        Add collection categories  # noqa: E501
        """
        pass

    def test_private_collection_categories_list(self):
        """Test case for private_collection_categories_list

        List collection categories  # noqa: E501
        """
        pass

    def test_private_collection_categories_replace(self):
        """Test case for private_collection_categories_replace

        Replace collection categories  # noqa: E501
        """
        pass

    def test_private_collection_category_delete(self):
        """Test case for private_collection_category_delete

        Delete collection category  # noqa: E501
        """
        pass

    def test_private_collection_create(self):
        """Test case for private_collection_create

        Create collection  # noqa: E501
        """
        pass

    def test_private_collection_delete(self):
        """Test case for private_collection_delete

        Delete collection  # noqa: E501
        """
        pass

    def test_private_collection_details(self):
        """Test case for private_collection_details

        Collection details  # noqa: E501
        """
        pass

    def test_private_collection_private_link_create(self):
        """Test case for private_collection_private_link_create

        Create collection private link  # noqa: E501
        """
        pass

    def test_private_collection_private_link_delete(self):
        """Test case for private_collection_private_link_delete

        Disable private link  # noqa: E501
        """
        pass

    def test_private_collection_private_link_update(self):
        """Test case for private_collection_private_link_update

        Update collection private link  # noqa: E501
        """
        pass

    def test_private_collection_private_links_list(self):
        """Test case for private_collection_private_links_list

        List collection private links  # noqa: E501
        """
        pass

    def test_private_collection_publish(self):
        """Test case for private_collection_publish

        Private Collection Publish  # noqa: E501
        """
        pass

    def test_private_collection_reserve_doi(self):
        """Test case for private_collection_reserve_doi

        Private Collection Reserve DOI  # noqa: E501
        """
        pass

    def test_private_collection_reserve_handle(self):
        """Test case for private_collection_reserve_handle

        Private Collection Reserve Handle  # noqa: E501
        """
        pass

    def test_private_collection_resource(self):
        """Test case for private_collection_resource

        Private Collection Resource  # noqa: E501
        """
        pass

    def test_private_collection_update(self):
        """Test case for private_collection_update

        Update collection  # noqa: E501
        """
        pass

    def test_private_collections_list(self):
        """Test case for private_collections_list

        Private Collections List  # noqa: E501
        """
        pass

    def test_private_collections_search(self):
        """Test case for private_collections_search

        Private Collections Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
