# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.institutions_api import InstitutionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInstitutionsApi(unittest.TestCase):
    """InstitutionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.institutions_api.InstitutionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_institution_curation(self):
        """Test case for account_institution_curation

        Institution Curation Review  # noqa: E501
        """
        pass

    def test_account_institution_curation_comments(self):
        """Test case for account_institution_curation_comments

        Institution Curation Review Comments  # noqa: E501
        """
        pass

    def test_account_institution_curation_comments_0(self):
        """Test case for account_institution_curation_comments_0

        POST Institution Curation Review Comment  # noqa: E501
        """
        pass

    def test_account_institution_curations(self):
        """Test case for account_institution_curations

        Institution Curation Reviews  # noqa: E501
        """
        pass

    def test_custom_fields_list(self):
        """Test case for custom_fields_list

        Private account institution group custom fields  # noqa: E501
        """
        pass

    def test_custom_fields_upload(self):
        """Test case for custom_fields_upload

        Custom fields values files upload  # noqa: E501
        """
        pass

    def test_institution_articles(self):
        """Test case for institution_articles

        Public Institution Articles  # noqa: E501
        """
        pass

    def test_institution_hrfeed_upload(self):
        """Test case for institution_hrfeed_upload

        Private Institution HRfeed Upload  # noqa: E501
        """
        pass

    def test_private_account_institution_user(self):
        """Test case for private_account_institution_user

        Private Account Institution User  # noqa: E501
        """
        pass

    def test_private_categories_list(self):
        """Test case for private_categories_list

        Private Account Categories  # noqa: E501
        """
        pass

    def test_private_group_embargo_options_details(self):
        """Test case for private_group_embargo_options_details

        Private Account Institution Group Embargo Options  # noqa: E501
        """
        pass

    def test_private_institution_account_group_role_delete(self):
        """Test case for private_institution_account_group_role_delete

        Delete Institution Account Group Role  # noqa: E501
        """
        pass

    def test_private_institution_account_group_roles(self):
        """Test case for private_institution_account_group_roles

        List Institution Account Group Roles  # noqa: E501
        """
        pass

    def test_private_institution_account_group_roles_create(self):
        """Test case for private_institution_account_group_roles_create

        Add Institution Account Group Roles  # noqa: E501
        """
        pass

    def test_private_institution_accounts_create(self):
        """Test case for private_institution_accounts_create

        Create new Institution Account  # noqa: E501
        """
        pass

    def test_private_institution_accounts_list(self):
        """Test case for private_institution_accounts_list

        Private Account Institution Accounts  # noqa: E501
        """
        pass

    def test_private_institution_accounts_search(self):
        """Test case for private_institution_accounts_search

        Private Account Institution Accounts Search  # noqa: E501
        """
        pass

    def test_private_institution_accounts_update(self):
        """Test case for private_institution_accounts_update

        Update Institution Account  # noqa: E501
        """
        pass

    def test_private_institution_articles(self):
        """Test case for private_institution_articles

        Private Institution Articles  # noqa: E501
        """
        pass

    def test_private_institution_details(self):
        """Test case for private_institution_details

        Private Account Institutions  # noqa: E501
        """
        pass

    def test_private_institution_embargo_options_details(self):
        """Test case for private_institution_embargo_options_details

        Private Account Institution embargo options  # noqa: E501
        """
        pass

    def test_private_institution_groups_list(self):
        """Test case for private_institution_groups_list

        Private Account Institution Groups  # noqa: E501
        """
        pass

    def test_private_institution_roles_list(self):
        """Test case for private_institution_roles_list

        Private Account Institution Roles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
