# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.articles_api import ArticlesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestArticlesApi(unittest.TestCase):
    """ArticlesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.articles_api.ArticlesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_article_report(self):
        """Test case for account_article_report

        Account Article Report  # noqa: E501
        """
        pass

    def test_account_article_report_generate(self):
        """Test case for account_article_report_generate

        Initiate a new Report  # noqa: E501
        """
        pass

    def test_article_details(self):
        """Test case for article_details

        View article details  # noqa: E501
        """
        pass

    def test_article_file_details(self):
        """Test case for article_file_details

        Article file details  # noqa: E501
        """
        pass

    def test_article_files(self):
        """Test case for article_files

        List article files  # noqa: E501
        """
        pass

    def test_article_version_confidentiality(self):
        """Test case for article_version_confidentiality

        Public Article Confidentiality for article version  # noqa: E501
        """
        pass

    def test_article_version_details(self):
        """Test case for article_version_details

        Article details for version  # noqa: E501
        """
        pass

    def test_article_version_embargo(self):
        """Test case for article_version_embargo

        Public Article Embargo for article version  # noqa: E501
        """
        pass

    def test_article_version_update(self):
        """Test case for article_version_update

        Update article version  # noqa: E501
        """
        pass

    def test_article_version_update_thumb(self):
        """Test case for article_version_update_thumb

        Update article version thumbnail  # noqa: E501
        """
        pass

    def test_article_versions(self):
        """Test case for article_versions

        List article versions  # noqa: E501
        """
        pass

    def test_articles_list(self):
        """Test case for articles_list

        Public Articles  # noqa: E501
        """
        pass

    def test_articles_search(self):
        """Test case for articles_search

        Public Articles Search  # noqa: E501
        """
        pass

    def test_private_article_author_delete(self):
        """Test case for private_article_author_delete

        Delete article author  # noqa: E501
        """
        pass

    def test_private_article_authors_add(self):
        """Test case for private_article_authors_add

        Add article authors  # noqa: E501
        """
        pass

    def test_private_article_authors_list(self):
        """Test case for private_article_authors_list

        List article authors  # noqa: E501
        """
        pass

    def test_private_article_authors_replace(self):
        """Test case for private_article_authors_replace

        Replace article authors  # noqa: E501
        """
        pass

    def test_private_article_categories_add(self):
        """Test case for private_article_categories_add

        Add article categories  # noqa: E501
        """
        pass

    def test_private_article_categories_list(self):
        """Test case for private_article_categories_list

        List article categories  # noqa: E501
        """
        pass

    def test_private_article_categories_replace(self):
        """Test case for private_article_categories_replace

        Replace article categories  # noqa: E501
        """
        pass

    def test_private_article_category_delete(self):
        """Test case for private_article_category_delete

        Delete article category  # noqa: E501
        """
        pass

    def test_private_article_confidentiality_delete(self):
        """Test case for private_article_confidentiality_delete

        Delete article confidentiality  # noqa: E501
        """
        pass

    def test_private_article_confidentiality_details(self):
        """Test case for private_article_confidentiality_details

        Article confidentiality details  # noqa: E501
        """
        pass

    def test_private_article_confidentiality_update(self):
        """Test case for private_article_confidentiality_update

        Update article confidentiality  # noqa: E501
        """
        pass

    def test_private_article_create(self):
        """Test case for private_article_create

        Create new Article  # noqa: E501
        """
        pass

    def test_private_article_delete(self):
        """Test case for private_article_delete

        Delete article  # noqa: E501
        """
        pass

    def test_private_article_details(self):
        """Test case for private_article_details

        Article details  # noqa: E501
        """
        pass

    def test_private_article_embargo_delete(self):
        """Test case for private_article_embargo_delete

        Delete Article Embargo  # noqa: E501
        """
        pass

    def test_private_article_embargo_details(self):
        """Test case for private_article_embargo_details

        Article Embargo Details  # noqa: E501
        """
        pass

    def test_private_article_embargo_update(self):
        """Test case for private_article_embargo_update

        Update Article Embargo  # noqa: E501
        """
        pass

    def test_private_article_file(self):
        """Test case for private_article_file

        Single File  # noqa: E501
        """
        pass

    def test_private_article_file_delete(self):
        """Test case for private_article_file_delete

        File Delete  # noqa: E501
        """
        pass

    def test_private_article_files_list(self):
        """Test case for private_article_files_list

        List article files  # noqa: E501
        """
        pass

    def test_private_article_private_link(self):
        """Test case for private_article_private_link

        List private links  # noqa: E501
        """
        pass

    def test_private_article_private_link_create(self):
        """Test case for private_article_private_link_create

        Create private link  # noqa: E501
        """
        pass

    def test_private_article_private_link_delete(self):
        """Test case for private_article_private_link_delete

        Disable private link  # noqa: E501
        """
        pass

    def test_private_article_private_link_update(self):
        """Test case for private_article_private_link_update

        Update private link  # noqa: E501
        """
        pass

    def test_private_article_publish(self):
        """Test case for private_article_publish

        Private Article Publish  # noqa: E501
        """
        pass

    def test_private_article_reserve_doi(self):
        """Test case for private_article_reserve_doi

        Private Article Reserve DOI  # noqa: E501
        """
        pass

    def test_private_article_reserve_handle(self):
        """Test case for private_article_reserve_handle

        Private Article Reserve Handle  # noqa: E501
        """
        pass

    def test_private_article_resource(self):
        """Test case for private_article_resource

        Private Article Resource  # noqa: E501
        """
        pass

    def test_private_article_update(self):
        """Test case for private_article_update

        Update article  # noqa: E501
        """
        pass

    def test_private_article_upload_complete(self):
        """Test case for private_article_upload_complete

        Complete Upload  # noqa: E501
        """
        pass

    def test_private_article_upload_initiate(self):
        """Test case for private_article_upload_initiate

        Initiate Upload  # noqa: E501
        """
        pass

    def test_private_articles_list(self):
        """Test case for private_articles_list

        Private Articles  # noqa: E501
        """
        pass

    def test_private_articles_search(self):
        """Test case for private_articles_search

        Private Articles search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
