# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.authors_api import AuthorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthorsApi(unittest.TestCase):
    """AuthorsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.authors_api.AuthorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_private_author_details(self):
        """Test case for private_author_details

        Author details  # noqa: E501
        """
        pass

    def test_private_authors_search(self):
        """Test case for private_authors_search

        Search Authors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
